server:
  port: 8761

spring:
  application:
    name: spring-cloud-swagger-eureka-example
  cloud:
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*
      preferred-networks:
        - 192.168
        - 10.0
eureka:
  instance:
    hostname: localhost 	#配置主机名
  client:
    #配置服务注册中心是否以自己为客户端进行注册(配置false)
    register-with-eureka: false
    #是否取得注册信息(配置false)
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #配置eureka客户端的缺省域(该配置可能没有提示,请复制或者手动输入,切勿使用有提示的service-url会引起内置tomcat报错)
